# Generated by Django 3.2 on 2021-08-07 16:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='media/default.png', max_length=255, verbose_name='profile_pics'),
        ),
    ]
