# Generated by Django 3.1.1 on 2020-10-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='media/blog.png', null=True, upload_to='image/'),
        ),
    ]
