# Generated by Django 3.2 on 2021-07-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_documents_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='media/blog.jpg', upload_to='image/'),
        ),
    ]
