# Generated by Django 3.2 on 2021-08-07 16:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(default='media/blog.jpg', max_length=255, verbose_name='image'),
        ),
    ]
