# Generated by Django 3.2 on 2021-08-07 16:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=cloudinary.models.CloudinaryField(default='media/blog.jpg', max_length=255, verbose_name='image'),
        ),
    ]
